project:
  type: website
  output-dir: docs

website:
  title: "Urban Insitute Employees Union"
  navbar:
    background: primary
    logo: www/images/urban_union_logo.jpeg
    left:
      - href: index.qmd
        text: Home
      - href: FAQ.qmd
        text: FAQ
      - href: about.qmd
        text: About Us
      - href: contact.qmd
        text: Contact

    right:
      - icon: github
        href: https://github.com/UrbanUnion
      - icon: twitter
        href: https://twitter.com/urbaninst_union
  page-footer: 
    center:
      - icon: envelope
        href: mailto:urbaninstituteunion@gmail.com
      - icon: github
        href: https://github.com/UrbanUnion
      - icon: twitter
        href: https://twitter.com/urbaninst_union
format:
  html:
    theme:
      light: 
        - flatly
        - www/flatly_custom_urban_union.scss
      dark:
        - darkly
        - www/darkly_custom_urban_union.scss
    toc: true
    image: www/images/urban_union_logo.jpeg
    image-alt: Urban Institute Employees Union Logo
    




