---
title: "FAQs"
---

## Basics

#### WHAT IS BARGAINING AND HOW DOES IT WORK?

Collective bargaining is the formal process employees in unions and their employers use to negotiatethe terms and conditions of work---including wages, benefits, and working conditions. The terms agreed upon during collective bargaining are solidified in a contract called the collective bargaining agreement (CBA).

The bargaining phase is eight steps:

-   *Bargaining Committee Formation* - represents the unit's interests in bargaining and negotiates a collective bargaining agreement with management
-   *Survey* - sent to the entire unit to gather information on the unit's priorities
-   *Request for Information* - gather facts from the employer to prior to negotiations
-   *Draft Articles* - As a bargaining committee we will draft sections of the contract we will bargain over. For example, we will write out our workplace benefits to present to Exec. *Ground Rules Bargaining* - guidelines that provides structure and process during bargaining
-   *CBA Bargaining* - organized contract around key priorities of the unit Ratification Vote - the unit votes to approve or reject a CBA
-   *CBA Signing by Unit, NPEU President, & Urban management* - a celebration should follow; it's a big deal!

Negotiations begin with current pay and benefits as the baseline. Members identify which issues are most important to them; areas that need improvement are often prioritized in bargaining. Negotiations can include anything that affects the conditions of your employment. While management is only legally obligated to bargain on wages, benefits, and other terms and conditions of employment, many NPEU members bargain on other important topics such as racial equity, professional development, and workplace democracy.

#### WHAT DOES IT MEAN TO BE IN THE STATUS QUO PERIOD?

We are currently in the status quo period with management before we have negotiated a first contract. During the status quo period, management can't make changes to the terms and conditions of your employment without notifying and bargaining with the union about these changes and their effects. That includes changes around issues like hours, wages, departmental procedures, benefits, leave, overtime, etc. The employer is also prohibited from conducting layoffs or furloughs without consulting and bargaining with the union on the impact of such decisions. Processes including raises, promotions, new hires, changing supervisors are NOT FROZEN in the status quo period, or after the status quo period.

#### WHAT IS A BARGAINING UNIT?

The bargaining unit is the group of employees at a workplace that make up the union. Generally, they share a "community of interest" (similar occupations, geographic location, duties, payment structure, review/rating system, etc.). A bargaining unit can include all the employees in a given office (i.e., wall-to-wall unit) or a set of occupations (e.g., professionals, clerical, technical, etc.). Most NPEU member organizations have "wall-to-wall" bargaining units that represent staff in all departments.

#### HOW WAS THE BARGAINING COMMITTEE FORMED?

The [Bargaining Committee](about.qmd#bargaining-committee) (BC) is a group of 11 self-nominated members representing a variety of roles, centers, and affinity groups. The BC works with representatives from the Nonprofit Professional Employees Union (NPEU) to prepare for negotiating a bargaining contract with executive management. There is opportunity for all union members to be involved with the bargaining process - email urbaninstituteunion\@gmail.com if you are interested in helping with bargaining tasks and union engagement.

## Bargaining

#### WHAT IS THE PROCESS OF DRAFTING A COLLECTIVE BARGAINING AGREEMENT?

Employees in unions and their employers can tailor the contract to the needs of their organization and its employees. A contract can include provisions such as improved wages, better benefits, greater work-life balance, professional development opportunities, protections that ensure fair and equal treatment, and other workplace improvements. We will work closely with our parent union NPEU to draft our collective bargaining agreement. NPEU has examples of previous contracts from other organizations to serve as guides for our contracts and lawyers to ensure our contract language meets legal benchmarks.

#### WHAT ARE SOME OF OUR UNION'S GOALS?

We are collaboratively working together to identify our goals as a union. Here are some of the issues we've identified and seek to address so far:

-   **Enhance Diversity and Inclusion**: We can... build on past efforts to enhance diversity, commit greater resources and authority to workers, and dismantle existing policies and norms that disadvantage people of marginalized identities. People of marginalized identities have different experiences working at Urban than their more privileged peers. We want all Urban employees, regardless of race, ethnicity, gender, physical ability, or sexual orientation to feel like their contributions are valued, heard, and respected.
-   **Promote Transparency**: We can... increase transparency in institutional decision making, facilitate more inclusive discussions of workplace issues between management and staff, better align Urban's internal practices with its mission, and set consistent policies across the institute so all workers at Urban can thrive. Urban values respect, honesty, opportunity, and collaboration. While Urban strives to honor these values in its research, it must work with intention to do the same in its internal structure and treatment of its own workers.
-   **Ensure Equitable Decision Making**: We can... require worker input in all major institutional decisions, ensure that organizational policies are fair to all employees, and hold managers accountable to good supervision. Equity is about sharing power. Urban is committed to equity and improving lives. To ensure a better workplace, Urban needs to allow workers a stronger voice and clear authority in institutional decision making.
-   **Fair Treatment and Compensation**: We can... foster a more respectful workplace, ensure everyone is fairly compensated for their work, and address concerns, grievances, and supervisory issues in a transparent and fair manner. Someone's experience at Urban shouldn't be dictated by their tenure, supervisor, or center or office. Everyone deserves a fair workplace.
-   **More Equitable Partnerships with Communities**: We can ...more wholly invest in the communities we work with, reduce extractive research methods, and include and compensate community members in our work. We want all our work at Urban to live up to our mission to "inform consequential choices about the well-being of people...in the United States" while enriching the lives of communities we work with.
-   **Boost Morale**: We can... reduce burnout, improve work-life balance, increase retention, improve research, and foster trust and fairness in the workplace. We want all Urban employees to have the resources and support to contribute to Urban's work.

These goals will continue to evolve as we survey unit members and get a better sense of the kinds of changes we want to see at Urban.

#### WHAT CAN WE ASK FOR?

The union is made up of Urban staff, and acts as an internal body (*made by us, run by us, decisions for us*) that has legal power to hold the executives accountable to us, their workers. Its purpose is not to be antagonistic or prevent collaboration between those who are in the union and those who are not. Its purpose is to make working conditions better for everyone, protect the most vulnerable workers, improve the transparency of decision making, and create accountability processes for the research we do. Employees in unions and their employers tailor their contract to the needs of their organization and its employees. Broadly, unions have legal status and power to effect change in a work environment. As long as there is a union, employers cannot unilaterally dictate wages, benefits, and other workplace policies. A contract can include provision categories such as:

-   Staff representation in strategic decisions, including Board participation
-   Policies to promote diversity, equity, and inclusion for staff based on race or ethnicity, gender, and disability status
-   Protections against harassment
-   Improved salary and promotion policies
-   Professional development opportunities
-   Processes to collaborate with managers
-   Health care, retirement, vacation time, sick leave, and paid family leave
-   Hiring, firing, disciplinary, and promotion policies
-   Telework, flex time, and overtime policies

Furthermore, after recognition but before a contract is finalized, there is a grace period granting workers additional protections and requiring management to consult the unit on decisions that will affect union staff. As an internal body with legal bargaining power, we will function as a check on our organization and will act as an accountability mechanism. Outside of contract negotiations, our union will allow us to put our metaphorical weight behind our recommendations, requests, and support for specific initiatives.

#### HOW MUCH ARE DUES AND HOW DO THEY WORK?

NPEU dues are 0.75% of pre-tax wages (about \$30/month for someone making \$50,000/year). Dues aren't collected until after the first contract is negotiated and ratified. All NPEU members pay dues through the standard direct deposit/payroll process at their workplace. These dues pay for:

-   Membership to the Local (NPEU), the International (IFPTE), and the AFL-CIO
-   Access to legal, training, bargaining, and support services from the Local and International
-   Access to NPEU events and annual meetings
-   Discretionary funds for events and solidarity activities (last year some these funds went to support BLM protests in DC)
-   Assistance if your employer violates your union contract

Generally these dues are more than offset by raises and additional benefits negotiated by the Union.

## Union Membership

#### WHO AT URBAN IS INCLUDED IN OUR BARGAINING UNIT?

Managerial authority differs by career track. We worked with people in each center and office and management to draw a line at what steps should, at minimum, be included in the union. For example, communications staff step one through four are automatically included in the union. Management also reserves the right to exclude certain people from the unit if they are privileged employees or require folks to sign NDAs before signing the unit. If you have any questions about your specific inclusion in the unit, get [in touch](contact.qmd) with us!

**Track Minimum Step Included**:

-   Accounting & Finance: Step 4
-   Center Operations: Step 5
-   Communications: Step 4
-   Development: Step 4
-   Executive Office: Step 3
-   Facilities & Office Services: Step 4
-   Grants and Contracts: Step 4
-   Human Resources: Step 3
-   Librarian: Step 3
-   Research, Policy, TTA: Step 3
-   Tech and Data: Step 4

#### WHAT HAPPENS IF SOMEONE IS PROMOTED OUT OF THE UNIT?

If someone is promoted to a step in their career track that exceeds the maximum step for eligibility, they will no longer be included in the unit. While they are not afforded the same benefits established in the CBA, Urbanites outside the bargaining unit have knowledge and connections are key to the success of the union. You are senior leaders who have power to support non-managerial staff through:

-   Advice or Guidance: As a leader at Urban, you have more experience with our institution and know more about its inner workings. You have knowledge that would be great to pass onto any members of the BC.
-   Support: You can be integral to the movement by publicly supporting the union and our efforts!
-   Outreach: If you know someone new in your center who is included in the bargaining unit, you can reach out to a member of the BC to help us get in contact with them.

Additionally, we hope that the improvements we bargain for will have positive spillover effects to everyone at Urban and not just those in the unit.

#### HOW MANY PEOPLE ARE IN OUR UNION?

As of 2022-11-05, there are 262 people in our unit.

## Your Rights

#### ARE THERE POTENTIAL REPERCUSSIONS FROM PUBLICLY DISCUSSING OR SUPPORTING THE UNION?

We have won the right to be proud and open about our union! And, it is illegal for an employer to retaliate against staff for working together to improve their workplace, including joining a union. Management and supervisory staff can't actively dissuade staff from participating in a unionizing effort and they can't reward staff for not participating. If you are still concerned about anonymity or your privacy and the bargaining process, please reach out to any member of the BC or send an email to urbaninstituteunion\@gmail.com. Additionally, over 140 senior staff (who are not part of the union) signed a letter in support of our union. You can find the letter (and your supervisors name or absence [here](https://www.google.com/url?q=https://supporting-urban-union.medium.com/supporting-urban-institute-staffs-efforts-to-organize-9104874ac58&sa=D&source=docs&ust=1652298481871940&usg=AOvVaw2BSTZGDD8K1vZMIvvS8_1A)).

#### WHAT LEGAL PROTECTIONS DO I HAVE?

Joining together with your coworkers to organize a union is a fundamental right recognized in U.S. labor law. It's even affirmed in the United Nations' Universal Declaration of Human Rights. Under the National Labor Relations Act, you have the right to:

-   Join a union
-   Talk to your coworkers and participate in meetings to discuss joining a union or other collective efforts to improve your workplace (outside of work hours)
-   Organize fellow employees, support the union, and distribute literature and membership cards to be signed
-   Sign a union membership card and demand employer recognition of your union
-   Wear buttons, stickers, T-shirts, etc. in support of the union
-   File complaints against your company if they are in violation of these rights

#### DOES OUR UNION MEAN THAT I CAN'T GO DIRECTLY TO MANAGEMENT WITH AN ISSUE?

No! You can continue to talk to your supervisor directly about issues at work---though it may not always get results. When you are represented, your union can help you talk with management on equal footing and with the support of your colleagues behind you. Having a fair process to resolve disputes is one of the most significant benefits of being in a union. If you have a disagreement with your employer, your union contract will lay out a specific process to help resolve your dispute. Your local union steward will support you in this process and will bring in support from NPEU and IFPTE if needed.

## Survey

#### HOW WILL ANONYMITY BE PROTECTED ON THE SURVEY?

It is important for us to ask demographic questions on the bargaining survey to ensure that our CBA includes priorities of traditionally deprioritized groups at Urban. However most of the demographic questions are optional. Individual answers to survey questions will NOT be viewed by anyone outside of the BC. All information presented back to the union will be aggregated and de-identified. We are creating a community of trust and hope that everyone feels comfortable taking the survey. If you do not, you can definitely provide feedback on policies you like/want to see changed by getting [in touch](contact.qmd) with any individual member of the BC who will report back anonymously.

#### HOW LONG WILL THE BARGAINING SURVEY BY FIELDED?

The survey will be open for three to four weeks. If the time frame does not work for you, please let us know and we will try to accommodate you. However, the sooner we have everyone's response, the quicker we can get to bargaining!

**Update**: The survey is closed as of Dec 2021.

#### I JOINED URBAN AFTER THE SURVEY WAS FIELDED, HOW CAN I PROVIDE FEEDBACK?

If you have feedback on specific policies you want to see changed at Urban, please get [in touch](contact.qmd) with us via email or reach out to a member of the BC directly.

#### HOW CAN I VIEW THE RESULTS OF THE SURVEY?

The BC presented the big picture aggregated results of the survey in our February 2022 Town Hall. If you want to see those slides, please reach out via email to urbaninstituteunion\@gmail.com

## Getting Involved

#### IS IT TOO LATE TO JOIN THE BARGAINING COMMITTEE?

No! Non-research staff and representatives from affinity groups are especially encouraged to join the Bargaining Committee. Please reach out to us at urbaninstituteunion\@gmail.com if you're interested in joining. We do have some turnover as folks leave Urban and will be looking for folks to come join the BC in the next few months.

#### WHAT ELSE CAN I DO AND WHO DO I CONTACT?

The Bargaining Committee is looking for volunteers to help with membership (talking to new members about the union to ensure they feel connected to our processes), bargaining (researching our current benefits and other policies that our unit is interested in improving), and other tasks as needed. You can fill out this [volunteer interest form](https://docs.google.com/forms/d/17d9XqYF-5BRa2fF70pnnx3Y0YOig82dY4Lb8V-LpWbM/edit?usp=sharing) to indicate interest in helping.

If you have any ideas about onboarding new hires to the union or increasing membership engagement, please feel free to reach out to vpancini\@urban.org.
